// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.Cert":       schema_pkg_apis_certoperator_v1beta1_Cert(ref),
		"github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertSpec":   schema_pkg_apis_certoperator_v1beta1_CertSpec(ref),
		"github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertStatus": schema_pkg_apis_certoperator_v1beta1_CertStatus(ref),
	}
}

func schema_pkg_apis_certoperator_v1beta1_Cert(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Cert is the Schema for the certs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertSpec", "github.com/fanfengqiang/cert-operator/pkg/apis/certoperator/v1beta1.CertStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_certoperator_v1beta1_CertSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertSpec defines the desired state of Cert",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_certoperator_v1beta1_CertStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertStatus defines the observed state of Cert",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
