apiVersion: certoperator.5ik8s.com/v1beta1
kind: Cert
metadata:
  name: fanfengqiang.com
spec:
  # Add fields here
  secretName: fanfengqiang.com
  domain: fanfengqiang.com
  email: "1415228958@qq.com"
  validityPeriod: 30
  provider: alidns
  envs:
    ALICLOUD_ACCESS_KEY: "LTAXXXXXXX1B35"
    ALICLOUD_SECRET_KEY: "7SO3AXXXXXXXXXXXXXXXXXXXtkpyMm"
