apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-operator
  template:
    metadata:
      labels:
        name: cert-operator
    spec:
      serviceAccountName: cert-operator
      containers:
        - name: cert-operator
          # Replace this with the built image name
          image: fanfengqiang/cert-operator:v1.1.0
          command:
          - cert-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cert-operator"


